version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
        environment:
            discovery.type: single-node
            indices.query.bool.max_clause_count: 4000
        ports:
            - "9200:9200"
        networks:
            - elastic
    kibana:
        image: docker.elastic.co/kibana/kibana:7.17.28
        ports:
            - "5601:5601"
        networks:
            - elastic
        depends_on:
            - elasticsearch
    filebeat:
        image: docker.elastic.co/beats/filebeat:7.17.28
        entrypoint: "filebeat -e -strict.perms=false"
        volumes:
            - ./malware-traffic-analysis.net:/logs:ro
            # - ./handson:/logs:ro
            - ./filebeat-config/suricata.yml:/usr/share/filebeat/modules.d/suricata.yml
        networks:
            - elastic
        depends_on:
            - elasticsearch
            - kibana
    loader:
        build: .
        volumes:
            - .:/datasets
        networks:
            - elastic
        depends_on:
            - elasticsearch
networks:
    elastic:
